// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID            uuid.UUID       `json:"id"`
	TenantID      uuid.UUID       `json:"tenant_id"`
	Severity      string          `json:"severity"`
	DetectionType string          `json:"detection_type"`
	SourceIp      string          `json:"source_ip"`
	AffectedAsset string          `json:"affected_asset"`
	Description   string          `json:"description"`
	Status        string          `json:"status"`
	Timestamp     time.Time       `json:"timestamp"`
	CreatedAt     time.Time       `json:"created_at"`
	Metadata      json.RawMessage `json:"metadata"`
}

type Honeytoken struct {
	ID              uuid.UUID    `json:"id"`
	TenantID        uuid.UUID    `json:"tenant_id"`
	Name            string       `json:"name"`
	Type            string       `json:"type"`
	TokenValue      string       `json:"token_value"`
	Status          string       `json:"status"`
	LastTriggeredAt sql.NullTime `json:"last_triggered_at"`
	CreatedAt       time.Time    `json:"created_at"`
}

type SecurityEvent struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	EventType string          `json:"event_type"`
	Source    string          `json:"source"`
	SourceIp  string          `json:"source_ip"`
	UserID    string          `json:"user_id"`
	Resource  string          `json:"resource"`
	Action    string          `json:"action"`
	Severity  string          `json:"severity"`
	Status    string          `json:"status"`
	Metadata  json.RawMessage `json:"metadata"`
	Timestamp time.Time       `json:"timestamp"`
	CreatedAt time.Time       `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
