// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countAlerts = `-- name: CountAlerts :one
SELECT COUNT(*) FROM alerts
WHERE tenant_id = $1
`

func (q *Queries) CountAlerts(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlerts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertsBySeverity = `-- name: CountAlertsBySeverity :many
SELECT severity, COUNT(*) as count FROM alerts
WHERE tenant_id = $1
GROUP BY severity
`

type CountAlertsBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountAlertsBySeverity(ctx context.Context, tenantID uuid.UUID) ([]CountAlertsBySeverityRow, error) {
	rows, err := q.db.QueryContext(ctx, countAlertsBySeverity, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAlertsBySeverityRow
	for rows.Next() {
		var i CountAlertsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFailedLoginsInWindow = `-- name: CountFailedLoginsInWindow :one
SELECT COUNT(*) FROM security_events
WHERE tenant_id = $1
  AND event_type = 'LOGIN_FAILED'
  AND (source_ip = $2 OR user_id = $3)
  AND timestamp >= $4
`

type CountFailedLoginsInWindowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	SourceIp  string    `json:"source_ip"`
	UserID    string    `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) CountFailedLoginsInWindow(ctx context.Context, arg CountFailedLoginsInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedLoginsInWindow,
		arg.TenantID,
		arg.SourceIp,
		arg.UserID,
		arg.Timestamp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecurityEvents = `-- name: CountSecurityEvents :one
SELECT COUNT(*) FROM security_events
WHERE tenant_id = $1
`

func (q *Queries) CountSecurityEvents(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecurityEvents, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, metadata, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, timestamp, created_at, metadata
`

type CreateAlertParams struct {
	ID            uuid.UUID       `json:"id"`
	TenantID      uuid.UUID       `json:"tenant_id"`
	Severity      string          `json:"severity"`
	DetectionType string          `json:"detection_type"`
	SourceIp      string          `json:"source_ip"`
	AffectedAsset string          `json:"affected_asset"`
	Description   string          `json:"description"`
	Status        string          `json:"status"`
	Metadata      json.RawMessage `json:"metadata"`
	Timestamp     time.Time       `json:"timestamp"`
}

// Alerts
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.ID,
		arg.TenantID,
		arg.Severity,
		arg.DetectionType,
		arg.SourceIp,
		arg.AffectedAsset,
		arg.Description,
		arg.Status,
		arg.Metadata,
		arg.Timestamp,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Severity,
		&i.DetectionType,
		&i.SourceIp,
		&i.AffectedAsset,
		&i.Description,
		&i.Status,
		&i.Timestamp,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const createHoneytoken = `-- name: CreateHoneytoken :one
INSERT INTO honeytokens (id, tenant_id, name, type, token_value, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, type, token_value, status, last_triggered_at, created_at
`

type CreateHoneytokenParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Name       string    `json:"name"`
	Type       string    `json:"type"`
	TokenValue string    `json:"token_value"`
	Status     string    `json:"status"`
}

// Honeytokens
func (q *Queries) CreateHoneytoken(ctx context.Context, arg CreateHoneytokenParams) (Honeytoken, error) {
	row := q.db.QueryRowContext(ctx, createHoneytoken,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.TokenValue,
		arg.Status,
	)
	var i Honeytoken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.TokenValue,
		&i.Status,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSecurityEvent = `-- name: CreateSecurityEvent :one
INSERT INTO security_events (id, tenant_id, event_type, source, source_ip, user_id, resource, action, severity, status, metadata, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, event_type, source, source_ip, user_id, resource, action, severity, status, metadata, timestamp, created_at
`

type CreateSecurityEventParams struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	EventType string          `json:"event_type"`
	Source    string          `json:"source"`
	SourceIp  string          `json:"source_ip"`
	UserID    string          `json:"user_id"`
	Resource  string          `json:"resource"`
	Action    string          `json:"action"`
	Severity  string          `json:"severity"`
	Status    string          `json:"status"`
	Metadata  json.RawMessage `json:"metadata"`
	Timestamp time.Time       `json:"timestamp"`
}

// Security Events
func (q *Queries) CreateSecurityEvent(ctx context.Context, arg CreateSecurityEventParams) (SecurityEvent, error) {
	row := q.db.QueryRowContext(ctx, createSecurityEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.Source,
		arg.SourceIp,
		arg.UserID,
		arg.Resource,
		arg.Action,
		arg.Severity,
		arg.Status,
		arg.Metadata,
		arg.Timestamp,
	)
	var i SecurityEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Source,
		&i.SourceIp,
		&i.UserID,
		&i.Resource,
		&i.Action,
		&i.Severity,
		&i.Status,
		&i.Metadata,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at
`

// Tenants
func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, role, created_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, timestamp, created_at, metadata FROM alerts
WHERE id = $1 AND tenant_id = $2
`

type GetAlertByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, arg.ID, arg.TenantID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Severity,
		&i.DetectionType,
		&i.SourceIp,
		&i.AffectedAsset,
		&i.Description,
		&i.Status,
		&i.Timestamp,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getHoneytokenByID = `-- name: GetHoneytokenByID :one
SELECT id, tenant_id, name, type, token_value, status, last_triggered_at, created_at FROM honeytokens
WHERE id = $1 AND tenant_id = $2
`

type GetHoneytokenByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetHoneytokenByID(ctx context.Context, arg GetHoneytokenByIDParams) (Honeytoken, error) {
	row := q.db.QueryRowContext(ctx, getHoneytokenByID, arg.ID, arg.TenantID)
	var i Honeytoken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.TokenValue,
		&i.Status,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHoneytokenByValue = `-- name: GetHoneytokenByValue :one
SELECT id, tenant_id, name, type, token_value, status, last_triggered_at, created_at FROM honeytokens
WHERE token_value = $1
`

func (q *Queries) GetHoneytokenByValue(ctx context.Context, tokenValue string) (Honeytoken, error) {
	row := q.db.QueryRowContext(ctx, getHoneytokenByValue, tokenValue)
	var i Honeytoken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.TokenValue,
		&i.Status,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSecurityEventByID = `-- name: GetSecurityEventByID :one
SELECT id, tenant_id, event_type, source, source_ip, user_id, resource, action, severity, status, metadata, timestamp, created_at FROM security_events
WHERE id = $1 AND tenant_id = $2
`

type GetSecurityEventByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetSecurityEventByID(ctx context.Context, arg GetSecurityEventByIDParams) (SecurityEvent, error) {
	row := q.db.QueryRowContext(ctx, getSecurityEventByID, arg.ID, arg.TenantID)
	var i SecurityEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Source,
		&i.SourceIp,
		&i.UserID,
		&i.Resource,
		&i.Action,
		&i.Severity,
		&i.Status,
		&i.Metadata,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, created_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertsFiltered = `-- name: ListAlertsFiltered :many
SELECT id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, timestamp, created_at, metadata FROM alerts
WHERE tenant_id = $1
  AND ($4::text IS NULL OR severity = $4)
  AND ($5::text IS NULL OR status = $5)
  AND ($6::text IS NULL OR detection_type = $6)
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAlertsFilteredParams struct {
	TenantID      uuid.UUID      `json:"tenant_id"`
	Limit         int32          `json:"limit"`
	Offset        int32          `json:"offset"`
	Severity      sql.NullString `json:"severity"`
	Status        sql.NullString `json:"status"`
	DetectionType sql.NullString `json:"detection_type"`
}

func (q *Queries) ListAlertsFiltered(ctx context.Context, arg ListAlertsFilteredParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsFiltered,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Severity,
		arg.Status,
		arg.DetectionType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Severity,
			&i.DetectionType,
			&i.SourceIp,
			&i.AffectedAsset,
			&i.Description,
			&i.Status,
			&i.Timestamp,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoneytokens = `-- name: ListHoneytokens :many
SELECT id, tenant_id, name, type, token_value, status, last_triggered_at, created_at FROM honeytokens
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHoneytokens(ctx context.Context, tenantID uuid.UUID) ([]Honeytoken, error) {
	rows, err := q.db.QueryContext(ctx, listHoneytokens, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Honeytoken
	for rows.Next() {
		var i Honeytoken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.TokenValue,
			&i.Status,
			&i.LastTriggeredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAlerts = `-- name: ListRecentAlerts :many
SELECT id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, timestamp, created_at, metadata FROM alerts
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentAlertsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListRecentAlerts(ctx context.Context, arg ListRecentAlertsParams) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAlerts, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Severity,
			&i.DetectionType,
			&i.SourceIp,
			&i.AffectedAsset,
			&i.Description,
			&i.Status,
			&i.Timestamp,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSecurityEvents = `-- name: ListRecentSecurityEvents :many
SELECT id, tenant_id, event_type, source, source_ip, user_id, resource, action, severity, status, metadata, timestamp, created_at FROM security_events
WHERE tenant_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type ListRecentSecurityEventsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListRecentSecurityEvents(ctx context.Context, arg ListRecentSecurityEventsParams) ([]SecurityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSecurityEvents, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecurityEvent
	for rows.Next() {
		var i SecurityEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Source,
			&i.SourceIp,
			&i.UserID,
			&i.Resource,
			&i.Action,
			&i.Severity,
			&i.Status,
			&i.Metadata,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityEventsFiltered = `-- name: ListSecurityEventsFiltered :many
SELECT id, tenant_id, event_type, source, source_ip, user_id, resource, action, severity, status, metadata, timestamp, created_at FROM security_events
WHERE tenant_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListSecurityEventsFilteredParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListSecurityEventsFiltered(ctx context.Context, arg ListSecurityEventsFilteredParams) ([]SecurityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSecurityEventsFiltered, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecurityEvent
	for rows.Next() {
		var i SecurityEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Source,
			&i.SourceIp,
			&i.UserID,
			&i.Resource,
			&i.Action,
			&i.Severity,
			&i.Status,
			&i.Metadata,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, created_at FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET status = $2
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, severity, detection_type, source_ip, affected_asset, description, status, timestamp, created_at, metadata
`

type UpdateAlertStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, updateAlertStatus, arg.ID, arg.Status, arg.TenantID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Severity,
		&i.DetectionType,
		&i.SourceIp,
		&i.AffectedAsset,
		&i.Description,
		&i.Status,
		&i.Timestamp,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const updateHoneytokenStatus = `-- name: UpdateHoneytokenStatus :one
UPDATE honeytokens
SET status = $2, last_triggered_at = $3
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, name, type, token_value, status, last_triggered_at, created_at
`

type UpdateHoneytokenStatusParams struct {
	ID              uuid.UUID    `json:"id"`
	Status          string       `json:"status"`
	LastTriggeredAt sql.NullTime `json:"last_triggered_at"`
	TenantID        uuid.UUID    `json:"tenant_id"`
}

func (q *Queries) UpdateHoneytokenStatus(ctx context.Context, arg UpdateHoneytokenStatusParams) (Honeytoken, error) {
	row := q.db.QueryRowContext(ctx, updateHoneytokenStatus,
		arg.ID,
		arg.Status,
		arg.LastTriggeredAt,
		arg.TenantID,
	)
	var i Honeytoken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.TokenValue,
		&i.Status,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateHoneytokenStatusByTokenID = `-- name: UpdateHoneytokenStatusByTokenID :one
UPDATE honeytokens
SET status = $2, last_triggered_at = $3
WHERE id = $1
RETURNING id, tenant_id, name, type, token_value, status, last_triggered_at, created_at
`

type UpdateHoneytokenStatusByTokenIDParams struct {
	ID              uuid.UUID    `json:"id"`
	Status          string       `json:"status"`
	LastTriggeredAt sql.NullTime `json:"last_triggered_at"`
}

func (q *Queries) UpdateHoneytokenStatusByTokenID(ctx context.Context, arg UpdateHoneytokenStatusByTokenIDParams) (Honeytoken, error) {
	row := q.db.QueryRowContext(ctx, updateHoneytokenStatusByTokenID, arg.ID, arg.Status, arg.LastTriggeredAt)
	var i Honeytoken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.TokenValue,
		&i.Status,
		&i.LastTriggeredAt,
		&i.CreatedAt,
	)
	return i, err
}
