// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAlerts(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountAlertsBySeverity(ctx context.Context, tenantID uuid.UUID) ([]CountAlertsBySeverityRow, error)
	CountFailedLoginsInWindow(ctx context.Context, arg CountFailedLoginsInWindowParams) (int64, error)
	CountSecurityEvents(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Alerts
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	// Honeytokens
	CreateHoneytoken(ctx context.Context, arg CreateHoneytokenParams) (Honeytoken, error)
	// Security Events
	CreateSecurityEvent(ctx context.Context, arg CreateSecurityEventParams) (SecurityEvent, error)
	// Tenants
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetHoneytokenByValue(ctx context.Context, tokenValue string) (Honeytoken, error)
	GetSecurityEventByID(ctx context.Context, arg GetSecurityEventByIDParams) (SecurityEvent, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListHoneytokens(ctx context.Context, tenantID uuid.UUID) ([]Honeytoken, error)
	ListRecentAlerts(ctx context.Context, arg ListRecentAlertsParams) ([]Alert, error)
	ListRecentSecurityEvents(ctx context.Context, arg ListRecentSecurityEventsParams) ([]SecurityEvent, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error)
	UpdateHoneytokenStatus(ctx context.Context, arg UpdateHoneytokenStatusParams) (Honeytoken, error)
}

var _ Querier = (*Queries)(nil)
